[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sereinity <sereinity@sereinity.fr>"]
edition = "2018"

[dependencies]
clap = {version = "2.32.0", features = ["yaml"]}
image = "0.20.1"
indicatif = "0.10.3"
nalgebra = "0.16.10"
rand = "0.5"
