[package]
name = "raytracing"
version = "0.1.0"
authors = ["Sereinity <sereinity@sereinity.fr>"]
edition = "2018"

[dependencies]
clap = {version = "4.3", features = ["derive"]}
image = "0.24"
indicatif = "0.17"
nalgebra = "0.32"
rand = "0.8"
rayon = "1.7"
