[package]
name = "raytracing"
version = "0.1.0"
authors = ["Sereinity <sereinity@sereinity.fr>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
image = "0.24"
indicatif = "0.16"
nalgebra = "0.31"
rand = "0.8"
rayon = "1.5"
