[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sereinity <sereinity@sereinity.fr>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
image = "0.23.4"
indicatif = "0.14.0"
nalgebra = "0.21.0"
rand = "0.7.3"
